// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: information.proto
// Protobuf C++ Version: 5.29.3

#include "information.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Information::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        room_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data2_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data3_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reqcode_{static_cast< ::RequestCode >(0)},
        rescode_{static_cast< ::ResponseCode >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Information::Information(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InformationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InformationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InformationDefaultTypeInternal() {}
  union {
    Information _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InformationDefaultTypeInternal _Information_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_information_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_information_2eproto = nullptr;
const ::uint32_t
    TableStruct_information_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Information, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Information, _impl_.user_name_),
        PROTOBUF_FIELD_OFFSET(::Information, _impl_.room_name_),
        PROTOBUF_FIELD_OFFSET(::Information, _impl_.data1_),
        PROTOBUF_FIELD_OFFSET(::Information, _impl_.data2_),
        PROTOBUF_FIELD_OFFSET(::Information, _impl_.data3_),
        PROTOBUF_FIELD_OFFSET(::Information, _impl_.reqcode_),
        PROTOBUF_FIELD_OFFSET(::Information, _impl_.rescode_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Information)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Information_default_instance_._instance,
};
const char descriptor_table_protodef_information_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021information.proto\"\237\001\n\013Information\022\021\n\tu"
    "ser_name\030\001 \001(\t\022\021\n\troom_name\030\002 \001(\t\022\r\n\005dat"
    "a1\030\003 \001(\t\022\r\n\005data2\030\004 \001(\t\022\r\n\005data3\030\005 \001(\t\022\035"
    "\n\007reqcode\030\006 \001(\0162\014.RequestCode\022\036\n\007rescode"
    "\030\007 \001(\0162\r.ResponseCode*\326\001\n\013RequestCode\022\016\n"
    "\nUSER_LOGIN\020\000\022\014\n\010REGISTER\020\001\022\024\n\020AES_DISTR"
    "IBUTION\020\002\022\024\n\020AUTO_CREATE_ROOM\020\003\022\026\n\022MANUA"
    "L_CREATE_ROOM\020\004\022\017\n\013SEARCH_ROOM\020\005\022\014\n\010BID_"
    "LORD\020\006\022\017\n\013PLAY_A_HAND\020\007\022\r\n\tGAME_OVER\020\010\022\014"
    "\n\010CONTINUE\020\t\022\016\n\nLEAVE_ROOM\020\n\022\010\n\004EXIT\020\013*\351"
    "\001\n\014ResponseCode\022\014\n\010LOGIN_OK\020\000\022\017\n\013REGISTE"
    "R_OK\020\001\022\024\n\020RSA_DISTRIBUTION\020\002\022\021\n\rAES_VERI"
    "FY_OK\020\003\022\020\n\014JOIN_ROOM_OK\020\004\022\016\n\nSTART_GAME\020"
    "\005\022\022\n\016SEARCH_ROOM_OK\020\006\022\016\n\nDEAL_CARDS\020\007\022\022\n"
    "\016OTHER_BID_LORD\020\010\022\025\n\021OTHER_PLAY_A_HAND\020\t"
    "\022\024\n\020OTHER_LEAVE_ROOM\020\n\022\n\n\006FAILED\020\013b\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_information_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_information_2eproto = {
    false,
    false,
    642,
    descriptor_table_protodef_information_2eproto,
    "information.proto",
    &descriptor_table_information_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_information_2eproto::offsets,
    file_level_enum_descriptors_information_2eproto,
    file_level_service_descriptors_information_2eproto,
};
const ::google::protobuf::EnumDescriptor* RequestCode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_information_2eproto);
  return file_level_enum_descriptors_information_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RequestCode_internal_data_[] = {
    786432u, 0u, };
bool RequestCode_IsValid(int value) {
  return 0 <= value && value <= 11;
}
const ::google::protobuf::EnumDescriptor* ResponseCode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_information_2eproto);
  return file_level_enum_descriptors_information_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t ResponseCode_internal_data_[] = {
    786432u, 0u, };
bool ResponseCode_IsValid(int value) {
  return 0 <= value && value <= 11;
}
// ===================================================================

class Information::_Internal {
 public:
};

Information::Information(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Information)
}
inline PROTOBUF_NDEBUG_INLINE Information::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Information& from_msg)
      : user_name_(arena, from.user_name_),
        room_name_(arena, from.room_name_),
        data1_(arena, from.data1_),
        data2_(arena, from.data2_),
        data3_(arena, from.data3_),
        _cached_size_{0} {}

Information::Information(
    ::google::protobuf::Arena* arena,
    const Information& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Information* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, reqcode_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, reqcode_),
           offsetof(Impl_, rescode_) -
               offsetof(Impl_, reqcode_) +
               sizeof(Impl_::rescode_));

  // @@protoc_insertion_point(copy_constructor:Information)
}
inline PROTOBUF_NDEBUG_INLINE Information::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_name_(arena),
        room_name_(arena),
        data1_(arena),
        data2_(arena),
        data3_(arena),
        _cached_size_{0} {}

inline void Information::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, reqcode_),
           0,
           offsetof(Impl_, rescode_) -
               offsetof(Impl_, reqcode_) +
               sizeof(Impl_::rescode_));
}
Information::~Information() {
  // @@protoc_insertion_point(destructor:Information)
  SharedDtor(*this);
}
inline void Information::SharedDtor(MessageLite& self) {
  Information& this_ = static_cast<Information&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_name_.Destroy();
  this_._impl_.room_name_.Destroy();
  this_._impl_.data1_.Destroy();
  this_._impl_.data2_.Destroy();
  this_._impl_.data3_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Information::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Information(arena);
}
constexpr auto Information::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Information),
                                            alignof(Information));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Information::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Information_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Information::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Information>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Information::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Information>(), &Information::ByteSizeLong,
            &Information::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Information, _impl_._cached_size_),
        false,
    },
    &Information::kDescriptorMethods,
    &descriptor_table_information_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Information::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 53, 2> Information::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Information>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string user_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Information, _impl_.user_name_)}},
    // string room_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Information, _impl_.room_name_)}},
    // string data1 = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Information, _impl_.data1_)}},
    // string data2 = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Information, _impl_.data2_)}},
    // string data3 = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(Information, _impl_.data3_)}},
    // .RequestCode reqcode = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Information, _impl_.reqcode_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(Information, _impl_.reqcode_)}},
    // .ResponseCode rescode = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Information, _impl_.rescode_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(Information, _impl_.rescode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_name = 1;
    {PROTOBUF_FIELD_OFFSET(Information, _impl_.user_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string room_name = 2;
    {PROTOBUF_FIELD_OFFSET(Information, _impl_.room_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string data1 = 3;
    {PROTOBUF_FIELD_OFFSET(Information, _impl_.data1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string data2 = 4;
    {PROTOBUF_FIELD_OFFSET(Information, _impl_.data2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string data3 = 5;
    {PROTOBUF_FIELD_OFFSET(Information, _impl_.data3_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .RequestCode reqcode = 6;
    {PROTOBUF_FIELD_OFFSET(Information, _impl_.reqcode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .ResponseCode rescode = 7;
    {PROTOBUF_FIELD_OFFSET(Information, _impl_.rescode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\13\11\11\5\5\5\0\0"
    "Information"
    "user_name"
    "room_name"
    "data1"
    "data2"
    "data3"
  }},
};

PROTOBUF_NOINLINE void Information::Clear() {
// @@protoc_insertion_point(message_clear_start:Information)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_name_.ClearToEmpty();
  _impl_.room_name_.ClearToEmpty();
  _impl_.data1_.ClearToEmpty();
  _impl_.data2_.ClearToEmpty();
  _impl_.data3_.ClearToEmpty();
  ::memset(&_impl_.reqcode_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.rescode_) -
      reinterpret_cast<char*>(&_impl_.reqcode_)) + sizeof(_impl_.rescode_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Information::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Information& this_ = static_cast<const Information&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Information::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Information& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Information)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_name = 1;
          if (!this_._internal_user_name().empty()) {
            const std::string& _s = this_._internal_user_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Information.user_name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string room_name = 2;
          if (!this_._internal_room_name().empty()) {
            const std::string& _s = this_._internal_room_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Information.room_name");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string data1 = 3;
          if (!this_._internal_data1().empty()) {
            const std::string& _s = this_._internal_data1();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Information.data1");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // string data2 = 4;
          if (!this_._internal_data2().empty()) {
            const std::string& _s = this_._internal_data2();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Information.data2");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string data3 = 5;
          if (!this_._internal_data3().empty()) {
            const std::string& _s = this_._internal_data3();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Information.data3");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // .RequestCode reqcode = 6;
          if (this_._internal_reqcode() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                6, this_._internal_reqcode(), target);
          }

          // .ResponseCode rescode = 7;
          if (this_._internal_rescode() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                7, this_._internal_rescode(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Information)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Information::ByteSizeLong(const MessageLite& base) {
          const Information& this_ = static_cast<const Information&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Information::ByteSizeLong() const {
          const Information& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Information)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string user_name = 1;
            if (!this_._internal_user_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_name());
            }
            // string room_name = 2;
            if (!this_._internal_room_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_room_name());
            }
            // string data1 = 3;
            if (!this_._internal_data1().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_data1());
            }
            // string data2 = 4;
            if (!this_._internal_data2().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_data2());
            }
            // string data3 = 5;
            if (!this_._internal_data3().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_data3());
            }
            // .RequestCode reqcode = 6;
            if (this_._internal_reqcode() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_reqcode());
            }
            // .ResponseCode rescode = 7;
            if (this_._internal_rescode() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_rescode());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Information::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Information*>(&to_msg);
  auto& from = static_cast<const Information&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Information)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_name().empty()) {
    _this->_internal_set_user_name(from._internal_user_name());
  }
  if (!from._internal_room_name().empty()) {
    _this->_internal_set_room_name(from._internal_room_name());
  }
  if (!from._internal_data1().empty()) {
    _this->_internal_set_data1(from._internal_data1());
  }
  if (!from._internal_data2().empty()) {
    _this->_internal_set_data2(from._internal_data2());
  }
  if (!from._internal_data3().empty()) {
    _this->_internal_set_data3(from._internal_data3());
  }
  if (from._internal_reqcode() != 0) {
    _this->_impl_.reqcode_ = from._impl_.reqcode_;
  }
  if (from._internal_rescode() != 0) {
    _this->_impl_.rescode_ = from._impl_.rescode_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Information::CopyFrom(const Information& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Information)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Information::InternalSwap(Information* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_name_, &other->_impl_.user_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.room_name_, &other->_impl_.room_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data1_, &other->_impl_.data1_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data2_, &other->_impl_.data2_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data3_, &other->_impl_.data3_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Information, _impl_.rescode_)
      + sizeof(Information::_impl_.rescode_)
      - PROTOBUF_FIELD_OFFSET(Information, _impl_.reqcode_)>(
          reinterpret_cast<char*>(&_impl_.reqcode_),
          reinterpret_cast<char*>(&other->_impl_.reqcode_));
}

::google::protobuf::Metadata Information::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_information_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
